smartvent_git/routes/web.php
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
                Route::post('orders/print_order', 'OrderController@orderPrint')->name('orders.print_order');
            });
           
           //Silder Route
            Route::namespace('Silders')->group(function () {
                Route::resource('silders', 'HomeSilderController');
                Route::get('silders','HomeSilderController@index')->name('silders.index');
                Route::get('silders/create', 'HomeSilderController@create')->name('silders.create');
                Route::get('silders/edit/{id}', 'HomeSilderController@edit')->name('silders.edit');
                Route::post('silders/store', 'HomeSilderController@store')->name('silders.store');
            });

            //Services Routes
             Route::namespace('Services')->group(function () {
                Route::resource('services', 'ServicesController');
                Route::get('services','ServicesController@index')->name('services.index');
                Route::get('services/create', 'ServicesController@create')->name('services.create');
                Route::get('services/edit/{id}', 'ServicesController@edit')->name('services.edit');
                Route::post('services/destroy/{id}', 'ServicesController@destroy')->name('services.destroy');
                Route::post('services/update/{id}', 'ServicesController@update')->name('services.update');
            });
            
           //CMS Content Route
             Route::namespace('CMS')->group(function () {
            // Route::resource('cmscontent', 'CmscontentController');

                Route::get('cmscontent','CmscontentController@index')->name('cmscontent.index');
                Route::get('cmscontent/create', 'CmscontentController@create')->name('cmscontent.create');
               
                Route::get('cmscontent/createfloodvent', 'CmscontentController@createfloodvent')->name('cmscontent.createfloodvent');
                Route::post('cmscontent/storefloodevnt', 'CmscontentController@storefloodevnt')->name('cmscontent.storefloodevnt');

                Route::get('cmscontent/createresidentl', 'CmscontentController@createresidentl')->name('cmscontent.createresidentl');
                Route::post('cmscontent/storeresidentl', 'CmscontentController@storeresidentl')->name('cmscontent.storeresidentl');
                Route::get('cmscontent/removeresidentl', 'CmscontentController@removeresidentl')->name('cmscontent.removeresidentl');
                Route::get('cmscontent/createcomrcl', 'CmscontentController@createcomrcl')->name('cmscontent.createcomrcl');
                Route::post('cmscontent/storecomrcl', 'CmscontentController@storecomrcl')->name('cmscontent.storecomrcl');
                Route::get('cmscontent/removecomrcl', 'CmscontentController@removecomrcl')->name('cmscontent.removecomrcl');
                Route::get('cmscontent/removeservice', 'CmscontentController@removeservice')->name('cmscontent.removeservice');
                
                // Route::get('cmscontent/createresidentl', 'CmscontentController@createresidentl')->name('cmscontent.createresidentl');
                // Route::post('cmscontent/storeresidentl', 'CmscontentController@storeresidentl')->name('cmscontent.storeresidentl');

                Route::get('cmscontent/createwhysmart', 'CmscontentController@createwhysmart')->name('cmscontent.createwhysmart');
                Route::post('cmscontent/storewhysmart', 'CmscontentController@storewhysmart')->name('cmscontent.storewhysmart');

                Route::get('cmscontent/createlokngsmrtvnt', 'CmscontentController@createlokngsmrtvnt')->name('cmscontent.createlokngsmrtvnt');
                Route::post('cmscontent/storelokngsmrtvnt', 'CmscontentController@storelokngsmrtvnt')->name('cmscontent.storelokngsmrtvnt');
                
                Route::get('cmscontent/createsmartvent', 'CmscontentController@createsmartvent')->name('cmscontent.createsmartvent');
                Route::post('cmscontent/storesmartvent', 'CmscontentController@storesmartvent')->name('cmscontent.storesmartvent');
                

                Route::get('cmscontent/createsmartventprodcts', 'CmscontentController@createsmartventprodcts')->name('cmscontent.createsmartventprodcts');
                Route::post('cmscontent/storesmartventprodcts', 'CmscontentController@storesmartventprodcts')->name('cmscontent.storesmartventprodcts');


                Route::get('cmscontent/createservices', 'CmscontentController@createservices')->name('cmscontent.createservices');
                Route::post('cmscontent/storeservices', 'CmscontentController@storeservices')->name('cmscontent.storeservices');
                


                Route::get('cmscontent/createlookingforsmrtvnt', 'CmscontentController@createlookingforsmrtvnt')->name('cmscontent.createlookingforsmrtvnt');
                Route::post('cmscontent/storelookingforsmrtvnt', 'CmscontentController@storelookingforsmrtvnt')->name('cmscontent.storelookingforsmrtvnt');


                Route::get('cmscontent/create', 'CmscontentController@create')->name('cmscontent.create');
                Route::get('cmscontent/edit/{id}', 'CmscontentController@edit')->name('cmscontent.edit');

            });

            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');
            
            Route::get('list-customer', 'Wallet\WalletController@index')->name('wallet.index');
            Route::get('wallet-show/{id}', 'Wallet\WalletController@walletSummery')->name('wallet.show');

        // });
        //Changed the employees to companies
        // Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('companies', 'CompaniesController');
            Route::get('companies/{id}/profile', 'CompaniesController@getProfile')->name('companies.profile');
            Route::get('remove-logo', 'CompaniesController@removeLogo')->name('company.remove.logo');
            
             Route::get('checksearch','CompaniesController@checkSearch')->name('companies.checksearch');
            Route::get('changeStatus', 'CompaniesController@changeStatus')->name('companies.status');
            Route::get('checkCompanyname', 'CompaniesController@checkCompanyname')->name('companies.checkCompanyname');
            Route::get('checkEditCompanyname', 'CompaniesController@checkEditCompanyname')->name('companies.checkEditCompanyname');
            Route::put('companies/{id}/profile', 'CompaniesController@updateProfile')->name('companies.profile.update');
           
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        // });
    });
    Route::get('translate','Admin\TranslateController@translate')->name('translate');
});


/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::match(['get','post'],'contactuscontactus','SendMealCCController@SendMail')->name('contactus.contactusSubmit');
Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Route::get('/update', 'HomeController@update')->name('home');
    Route::match(['get','post'],'contact','SendMailController@SendMail')->name('contact.contactFormSubmit');
    
    Route::group(['middleware' => ['auth', 'web']], function () {
        //contact
        // Route::post('contact', 'HomeController@contactFormSubmit')->name('contact.contactFormSubmit');
 
        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    Route::get("search", 'ProductController@search')->name('search.product');

smartvent_git/app/Http/Controllers/Admin/Brands/BrandController.php
<?php

namespace App\Http\Controllers\Admin\Brands;

use App\Http\Controllers\Controller;
use App\Shop\Brands\Repositories\BrandRepository;
use App\Shop\Brands\Repositories\BrandRepositoryInterface;
use App\Shop\Brands\Requests\CreateBrandRequest;
use App\Shop\Brands\Requests\UpdateBrandRequest;

class BrandController extends Controller
{
    /**
     * @var BrandRepositoryInterface
     */
    private $brandRepo;

    /**
     * BrandController constructor.
     *
     * @param BrandRepositoryInterface $brandRepository
     */
    public function __construct(BrandRepositoryInterface $brandRepository)
    {
        $this->brandRepo = $brandRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data = $this->brandRepo->paginateArrayResults($this->brandRepo->listBrands(['*'], 'name', 'asc')->all());

        return view('admin.brands.list', ['brands' => $data]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.brands.create');
    }

    /**
     * @param CreateBrandRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateBrandRequest $request)
    {
        $this->brandRepo->createBrand($request->all());

        return redirect()->route('admin.brands.index')->with('message', 'Create brand successful!');
    }

    /**
     * @param $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        return view('admin.brands.edit', ['brand' => $this->brandRepo->findBrandById($id)]);
    }

    /**
     * @param UpdateBrandRequest $request
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws \App\Shop\Brands\Exceptions\UpdateBrandErrorException
     */
    public function update(UpdateBrandRequest $request, $id)
    {
        $brand = $this->brandRepo->findBrandById($id);

        $brandRepo = new BrandRepository($brand);
        $brandRepo->updateBrand($request->all());

        return redirect()->route('admin.brands.edit', $id)->with('message', 'Update successful!');
    }

    /**
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $brand = $this->brandRepo->findBrandById($id);

        $brandRepo = new BrandRepository($brand);
        $brandRepo->dissociateProducts();
        $brandRepo->deleteBrand();

        return redirect()->route('admin.brands.index')->with('message', 'Delete successful!');
    }
}

smartvent_git/resources/views/admin/brands/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.brands.store') }}" method="post" class="form" enctype="multipart/form-data">
                <div class="box-body">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{{ old('name') }}">
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.brands.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

smartvent_git/resources/views/admin/brands/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.brands.update', $brand->id) }}" method="post" class="form" enctype="multipart/form-data">
                <div class="box-body">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                        <label for="name">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{{ $brand->name }}">
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.brands.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

smartvent_git/resources/views/admin/brands/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if(!$brands->isEmpty())
            <div class="box">
                <div class="box-body">
                    <h2>Brands</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <td>Name</td>
                                <td>Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($brands as $brand)
                            <tr>
                                <td>
                                    <a href="{{ route('admin.brands.show', $brand->id) }}">{{ $brand->name }}</a>
                                </td>
                                <td>
                                    <form action="{{ route('admin.brands.destroy', $brand->id) }}" method="post" class="form-horizontal">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            <a href="{{ route('admin.brands.edit', $brand->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $brands->links() }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            @else
            <p class="alert alert-warning">No brand created yet. <a href="{{ route('admin.brands.create') }}">Create one!</a></p>
        @endif
    </section>
    <!-- /.content -->
@endsection