smartvent_git/routes/web.php
                Route::post('destroy/{id}', 'CountryDataController@destroy')->name('country_data.destroy');
                Route::post('destroydistrict/{id}', 'CountryDataController@destroydistrict')->name('country_data.destroydistrict');
                Route::post('destroytehsil/{id}', 'CountryDataController@destroytehsil')->name('country_data.destroytehsil');
                Route::post('country_data/destroyvillage/{id}', 'CountryDataController@destroyvillage')->name('country_data.destroyvillage');
                Route::post('getCity', 'CountryDataController@getCity')->name('country_data.getCity');
                Route::post('getTehsil', 'CountryDataController@getTehsil')->name('country_data.getTehsil');
                Route::get('createVillage','CountryDataController@createVillage')->name('country_data.createVillage');
                Route::get('createCity','CountryDataController@createCity')->name('country_data.createCity');
                Route::post('state-store','CountryDataController@stateStore')->name('country_data.state_store');
                
                // Disritct
                Route::get('disritct-edit/{id}','CountryDataController@disritctEdit')->name('country_data.disritct_edit');
                Route::post('disritct-update','CountryDataController@disritctUpdate')->name('country_data.disritct_update');
                
                // Edit Tehsil
                Route::get('tehsil-edit/{id}','CountryDataController@tehsilEdit')->name('country_data.tehsil_edit');
                Route::post('tehsil-store','CountryDataController@tehsilStore')->name('country_data.update_tehsil');
                
                // Village
                Route::get('village-edit/{id}','CountryDataController@villageEdit')->name('country_data.village_edit');
                Route::post('village-update','CountryDataController@villageUpdate')->name('country_data.village_update');
                
                
            });

            Route::namespace('Priorities')->group(function () {
                Route::resource('pro_priority', 'PriorityController');
                // Route::post('update', 'PriorityController@update');
                Route::post('pro_priority/sort', 'PriorityController@cat_sort')->name('priority.sort');
                Route::post('pro_priority/subcat_sort', 'PriorityController@subcat_sort')->name('priority.subcat_sort');
                Route::post('pro_priority/getProduct', 'PriorityController@getProduct')->name('priority.getProduct');
                Route::post('pro_priority/getCategoryProduct', 'PriorityController@getCategoryProduct')->name('priority.getCategoryProduct');
                Route::post('pro_priority/getAllProduct', 'PriorityController@getAllProduct')->name('priority.getAllProduct');
            });
            Route::namespace('Users')->group(function () {
                Route::get('users', 'UsersController@index')->name('users.index');
                Route::get('users/create', 'UsersController@create')->name('users.create');
                Route::get('users/edit/{id}', 'UsersController@edit')->name('users.edit');
                Route::post('users/store', 'UsersController@store')->name('users.store');
                Route::post('users/destroy/{id}', 'UsersController@destroy')->name('users.destroy');
            });
            Route::namespace('Offers')->group(function () {
                Route::resource('offers', 'OffersController');
                Route::get('offers_product','OffersController@getProduct')->name('offers.product.attr');
                Route::post('offers/{id}', 'OffersController@update')->name('offers.update');
                Route::get('remove-image-offer', 'OffersController@removeImage')->name('offers.remove.image');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Orders')->group(function () {
                Route::get('orders/printorder','OrderController@printInvoice')->name('orders.print_invoice');
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
                Route::post('orders/print_order', 'OrderController@orderPrint')->name('orders.print_order');
            });
           
           //Silder Route
            Route::namespace('Silders')->group(function () {
                Route::resource('silders', 'HomeSilderController');
                Route::get('silders','HomeSilderController@index')->name('silders.index');
                Route::get('silders/create', 'HomeSilderController@create')->name('silders.create');
                Route::get('silders/edit/{id}', 'HomeSilderController@edit')->name('silders.edit');
                Route::post('silders/store', 'HomeSilderController@store')->name('silders.store');
            });

            //Services Routes
             Route::namespace('Services')->group(function () {
                Route::resource('services', 'ServicesController');
                Route::get('services','ServicesController@index')->name('services.index');
                Route::get('services/create', 'ServicesController@create')->name('services.create');
                Route::get('services/edit/{id}', 'ServicesController@edit')->name('services.edit');
                Route::post('services/destroy/{id}', 'ServicesController@destroy')->name('services.destroy');
                Route::post('services/update/{id}', 'ServicesController@update')->name('services.update');
            });
            
           //CMS Content Route
             Route::namespace('CMS')->group(function () {
            // Route::resource('cmscontent', 'CmscontentController');

                Route::get('cmscontent','CmscontentController@index')->name('cmscontent.index');
                Route::get('cmscontent/create', 'CmscontentController@create')->name('cmscontent.create');
               
                Route::get('cmscontent/createfloodvent', 'CmscontentController@createfloodvent')->name('cmscontent.createfloodvent');
                Route::post('cmscontent/storefloodevnt', 'CmscontentController@storefloodevnt')->name('cmscontent.storefloodevnt');

                Route::get('cmscontent/createresidentl', 'CmscontentController@createresidentl')->name('cmscontent.createresidentl');
                Route::post('cmscontent/storeresidentl', 'CmscontentController@storeresidentl')->name('cmscontent.storeresidentl');
                Route::get('cmscontent/removeresidentl', 'CmscontentController@removeresidentl')->name('cmscontent.removeresidentl');
                Route::get('cmscontent/createcomrcl', 'CmscontentController@createcomrcl')->name('cmscontent.createcomrcl');
                Route::post('cmscontent/storecomrcl', 'CmscontentController@storecomrcl')->name('cmscontent.storecomrcl');
                Route::get('cmscontent/removecomrcl', 'CmscontentController@removecomrcl')->name('cmscontent.removecomrcl');
                Route::get('cmscontent/removeservice', 'CmscontentController@removeservice')->name('cmscontent.removeservice');
                
                // Route::get('cmscontent/createresidentl', 'CmscontentController@createresidentl')->name('cmscontent.createresidentl');
                // Route::post('cmscontent/storeresidentl', 'CmscontentController@storeresidentl')->name('cmscontent.storeresidentl');

                Route::get('cmscontent/createwhysmart', 'CmscontentController@createwhysmart')->name('cmscontent.createwhysmart');
                Route::post('cmscontent/storewhysmart', 'CmscontentController@storewhysmart')->name('cmscontent.storewhysmart');

                Route::get('cmscontent/createlokngsmrtvnt', 'CmscontentController@createlokngsmrtvnt')->name('cmscontent.createlokngsmrtvnt');
                Route::post('cmscontent/storelokngsmrtvnt', 'CmscontentController@storelokngsmrtvnt')->name('cmscontent.storelokngsmrtvnt');
                
                Route::get('cmscontent/createsmartvent', 'CmscontentController@createsmartvent')->name('cmscontent.createsmartvent');
                Route::post('cmscontent/storesmartvent', 'CmscontentController@storesmartvent')->name('cmscontent.storesmartvent');
                

                Route::get('cmscontent/createsmartventprodcts', 'CmscontentController@createsmartventprodcts')->name('cmscontent.createsmartventprodcts');
                Route::post('cmscontent/storesmartventprodcts', 'CmscontentController@storesmartventprodcts')->name('cmscontent.storesmartventprodcts');


                Route::get('cmscontent/createservices', 'CmscontentController@createservices')->name('cmscontent.createservices');
                Route::post('cmscontent/storeservices', 'CmscontentController@storeservices')->name('cmscontent.storeservices');
                


                Route::get('cmscontent/createlookingforsmrtvnt', 'CmscontentController@createlookingforsmrtvnt')->name('cmscontent.createlookingforsmrtvnt');
                Route::post('cmscontent/storelookingforsmrtvnt', 'CmscontentController@storelookingforsmrtvnt')->name('cmscontent.storelookingforsmrtvnt');


                Route::get('cmscontent/create', 'CmscontentController@create')->name('cmscontent.create');
                Route::get('cmscontent/edit/{id}', 'CmscontentController@edit')->name('cmscontent.edit');

            });

            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');

smartvent_git/app/Http/Controllers/RESTAPIs/v1/customer/OfferController.php
<?php

namespace App\Http\Controllers\RestAPIs\v1\customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Shop\Offers\Offer;
use App\Shop\Offers\OfferProduct;
use App\Shop\Products\Product;
use Validator;
use App\Helper\MailHelper;
use App\Helper\ResponseMessage;

class OfferController extends Controller
{
    public function offer(Request $request) 
    {
    	try {
    		$current_date =  date('Y-m-d');
    		date_default_timezone_set('Asia/Kolkata');
    		$current_time = date( 'H:i:s');
            $getoffr=array();
            $offerquery = Offer::query();
            if($request->get('userdetail')){
                if($request->get('userdetail')->language=="hi"){
                    $offerquery->select('id', 'offer_hi as offer', 'cover', 'description_hi as description');
                } else if($request->get('userdetail')->language=="gu"){
                    $offerquery->select('id', 'offer_gu as offer', 'cover', 'description_gu      as description');
                } else{
                    $offerquery->select('id', 'offer', 'cover', 'description');
                }
            } else{
                $offerquery->select('id', 'offer', 'cover', 'description');
            }
            $offers = $offerquery->where('expired_date', '>=', $current_date)
                            ->where('status', 1)
                            ->get();
           // $offers['mobile_no']=env('COMPANY_MOBNO');
           foreach($offers as $ofr){
 $getoffr=['id'=>$ofr->id,'offer'=>$ofr->offer,'cover'=>$ofr->cover,'description'=>$ofr->description];
           }
			if(count($offers)==0) {
				$offers=[];
			}
			//
			$test=array();
			$test=['mobile_no'=>env('COMPANY_MOBNO')];
			//$offers['mobile_no']=env('COMPANY_MOBNO');
		   // $abc=array();
		   $data=array();
		   $data['status']=200;
		   $data['message']='Success';
		   $data['data']=$offers;
		   $data['mobile']=env('COMPANY_MOBNO');
	return json_encode($data);

		//	ResponseMessage::success("Success",$offers );
    	} catch (Exception $e) {
    		log::error($e);
			$data['error']=$e;
			$error_mail = MailHelper::errorMail($data);
    	}
    }
    
    public function getOffer(Request $request) 
    {
        try {
            $rules = [
                'offer_id' => 'required',
            ];
            $customeMessage = [
                'offer_id.required' => 'Please enter offer id.',
            ];
            $validator = Validator::make($request->all(),$rules, $customeMessage);

            if( $validator->fails() ) {
                $errors = $validator->errors();
                ResponseMessage::error($errors->first());
            } else {
                $offer_id = trim(strip_tags($request->offer_id));
                if(Offer::where('id',$offer_id)->where('status',1)->exists()) {
                    if(OfferProduct::where('offer_id', $offer_id)->exists()) {

                        $offerquery = OfferProduct::query();
                        $offerquery->join('products','products.id','offer_product.product_id')
                                   ->join('product_attribute', 'product_attribute.id','offer_product.attribute_id');
                        if($request->get('userdetail')){
                            if($request->get('userdetail')->language=="hi"){
                                $offerquery->select('products.id','products.name_hi as name','product_attribute.price','product_attribute.sale_price','products.cover');
                            } else if($request->get('userdetail')->language=="gu"){
                                $offerquery->select('products.id','products.name_gu as name','product_attribute.price','product_attribute.sale_price','products.cover');
                            } else{
                                $offerquery->select('products.id','products.name','product_attribute.price','product_attribute.sale_price','products.cover');
                            }
                        } else{
                            $offerquery->select('products.id','products.name','product_attribute.price','product_attribute.sale_price','products.cover');
                        }   
                        $products = $offerquery->where('offer_id', $offer_id)
                                                ->where('products.status',1)
                                                ->get();
                        ResponseMessage::success('Success', $products);
                    } else {
                        ResponseMessage::error('Offer product not found!!');
                    }
                } else {
                    ResponseMessage::error('Offer not found!!');
                }
            }
        } catch (Exception $e) {
            log::error($e);
			$data['error']=$e;
			$error_mail = MailHelper::errorMail($data);
        }
    }
}

smartvent_git/resources/views/admin/offers/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($offers)
            <div class="box">
                <div class="box-body">
                    <div class="box-body">
                        <div class="box-header with-border bg-title border-header">
                            <h4 class="page-title header-color">Manage Offers</h4>
                        </div>
                    </div>
                    <div class="box-body">
                        <table class="table border-b1px" id="table-id">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Offer</th>
                                    <th>Offer Type</th>
                                    <!-- <th>Company Name</th>
                                    <th>Category Name</th> -->
                                    <th>Expired Date</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            @php
                                $i=1;
                            @endphp
                            @foreach ($offers as $offer)
                                <tr>
                                    <!-- <td><a href="{{ route('admin.offers.show', $offer->id) }}">{{ $offer->offer_type }}</a></td> -->
                                    <td>{{ $i++ }}</td>
                                    <td>{{ ucfirst($offer->offer) }}</td>
                                    <td>@if($offer->offer_type=="single_offer") Single Offer @else Combo Offer  @endif</td>
                                    <!-- <td>{{ $offer->company }}</td>
                                    <td>{{ $offer->category }}</td> -->
                                    @php 
                                       $newDate = date("d/m/Y", strtotime($offer->expired_date)); 
                                    @endphp
                                    <td>{{ $newDate }}</td>
                                    <td>@include('layouts.status', ['status' => $offer->status])</td>
                                    <td>
                                        <form action="{{ route('admin.offers.destroy', $offer->id) }}" method="post" class="form-horizontal">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="delete">
                                            <div class="btn-group">
                                                @if($permission->edit==1)
                                                    <a href="{{ route('admin.offers.edit', $offer->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                                @endif
                                                @if($permission->delete==1)
                                                    <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>
                                                @endif
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $offers->links() }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @else
            <div class="box">
                <div class="box-body"><p class="alert alert-warning">No offers found.</p></div>
            </div>
        @endif

    </section>
    <!-- /.content -->
@endsection

@section('js')
<script>
    $(document).ready(function() {
        $('#table-id').DataTable();
    } );
</script>
@endsection

smartvent_git/resources/views/admin/offers/show.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($offer)
            <div class="box">
                <div class="box-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <td class="col-md-2">Offer  Type</td>
                            <td class="col-md-3">Cover</td>
                            <td class="col-md-2">Expired Date</td>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ $offer->offer_type }}</td>
                                <td>
                                    @if(isset($offer->cover))
                                        <img src="{{ asset("storage/app/public/cover/$offer->cover") }}" class="img-responsive" alt="">
                                    @endif
                                </td>
                                <td>{{ $offer->expired_date }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.offers.index') }}" class="btn btn-default btn-sm">Back</a>
                    </div>
                </div>
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection