smartvent_git/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        // Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
                Route::post('getCategories', 'ProductController@getCategories')->name('products.getCategories');
                Route::post('getCropCategories', 'ProductController@getCropCategories')->name('products.getCropCategories');
                Route::post('getSubCropCategories', 'ProductController@getSubCropCategories')->name('products.getSubCropCategories');
                  Route::get('checkProductname', 'ProductController@checkProductname')->name('products.checkProductname');
                  Route::get('checkEditProductname', 'ProductController@checkEditProductname')->name('products.checkEditProductname');
                Route::post('getSubCategories', 'ProductController@getSubCategories')->name('products.getSubCategories');
                Route::get('checkhsncode', 'ProductController@checkHsnCode')->name('products.checkhsncode');
                Route::post('getTechnicalName', 'ProductController@getTechnicalName')->name('products.getTechnicalName');
                Route::post('getProductTechnical', 'ProductController@getProductTechnical')->name('products.getProductTechnical');

            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            // Route::namespace('Crop')->group(function () {
            //     Route::resource('crops', 'CropController');
            // });
            Route::namespace('Crops')->group(function () {
                Route::resource('crops', 'CropController');
                Route::get('crops/create/{id?}', 'CropController@create')->name('crops.create');
                Route::get('crops/subcrop/{id}/{subcat?}', 'CropController@showSub')->name('crops.show_sub');
                Route::get('crops/subcrop/create/{id?}/{subcat?}', 'CropController@subCreate')->name('crops.sub_create');
                Route::get('crops/getsubcat/{id}', 'CropController@getSubcat')->name('crops.getsubcat');
                Route::post('crops/substore', 'CropController@subStore')->name('crops.subcatstore');
                Route::get('crops/subcrop/edit/{id}/{cat}/{subcat}', 'CropController@subEdit')->name('crops.sub_edit');
                Route::get('checkSubsolutionname', 'CropController@checkSubsolutionname')->name('crops.checkSubsolutionname');
              Route::get('checkEditSubsolutionname', 'CropController@checkEditSubsolutionname')->name('crops.checkEditSubsolutionname');
                
            });
            
            Route::namespace('CustomerNotifications')->group(function () {
                Route::post('getValue', 'NotificationController@getValue')->name('notifications.getValue');
                Route::resource('notifications', 'NotificationController');
            });
            
            Route::namespace('TechnicalCategoties')->group(function () {
                Route::resource('technical', 'TechnicalController');
            });

            Route::namespace('UpdateStocks')->group(function () {
                Route::resource('updateStock', 'UpdateStockController');
            });
            
            
            Route::namespace('CountriesData')->group(function () {
                Route::resource('country_data', 'CountryDataController');
                Route::get('country_data/show-tehsil/{id?}', 'CountryDataController@showTehsil')->name('country_data.showTehsil');
                Route::get('country_data/show-village/{id?}', 'CountryDataController@showVillage')->name('country_data.showVillage');
                //Route::get('country_data/destroy-village/{id?}', 'CountryDataController@destroyVillage')->name('country_data.destroyVillage');
                Route::get('checkDistrictname', 'CountryDataController@checkDistrictname')->name('country_data.checkDistrictname');
                Route::get('checkEditDistrictname', 'CountryDataController@checkEditDistrictname')->name('country_data.checkEditDistrictname');
                Route::get('checkTehsilname', 'CountryDataController@checkTehsilname')->name('country_data.checkTehsilname');
                Route::get('checkEditTehsilname', 'CountryDataController@checkEditTehsilname')->name('country_data.checkEditTehsilname');
                Route::get('checkVillagename', 'CountryDataController@checkVillagename')->name('country_data.checkVillagename');
                Route::get('checkEditVillagename', 'CountryDataController@checkEditVillagename')->name('country_data.checkEditVillagename');
                Route::post('destroy/{id}', 'CountryDataController@destroy')->name('country_data.destroy');
                Route::post('destroydistrict/{id}', 'CountryDataController@destroydistrict')->name('country_data.destroydistrict');
                Route::post('destroytehsil/{id}', 'CountryDataController@destroytehsil')->name('country_data.destroytehsil');
                Route::post('country_data/destroyvillage/{id}', 'CountryDataController@destroyvillage')->name('country_data.destroyvillage');
                Route::post('getCity', 'CountryDataController@getCity')->name('country_data.getCity');
                Route::post('getTehsil', 'CountryDataController@getTehsil')->name('country_data.getTehsil');
                Route::get('createVillage','CountryDataController@createVillage')->name('country_data.createVillage');
                Route::get('createCity','CountryDataController@createCity')->name('country_data.createCity');
                Route::post('state-store','CountryDataController@stateStore')->name('country_data.state_store');
                
                // Disritct
                Route::get('disritct-edit/{id}','CountryDataController@disritctEdit')->name('country_data.disritct_edit');
                Route::post('disritct-update','CountryDataController@disritctUpdate')->name('country_data.disritct_update');
                
                // Edit Tehsil
                Route::get('tehsil-edit/{id}','CountryDataController@tehsilEdit')->name('country_data.tehsil_edit');
                Route::post('tehsil-store','CountryDataController@tehsilStore')->name('country_data.update_tehsil');
                
                // Village
                Route::get('village-edit/{id}','CountryDataController@villageEdit')->name('country_data.village_edit');
                Route::post('village-update','CountryDataController@villageUpdate')->name('country_data.village_update');
                
                
            });

            Route::namespace('Priorities')->group(function () {
                Route::resource('pro_priority', 'PriorityController');
                // Route::post('update', 'PriorityController@update');
                Route::post('pro_priority/sort', 'PriorityController@cat_sort')->name('priority.sort');
                Route::post('pro_priority/subcat_sort', 'PriorityController@subcat_sort')->name('priority.subcat_sort');
                Route::post('pro_priority/getProduct', 'PriorityController@getProduct')->name('priority.getProduct');
                Route::post('pro_priority/getCategoryProduct', 'PriorityController@getCategoryProduct')->name('priority.getCategoryProduct');
                Route::post('pro_priority/getAllProduct', 'PriorityController@getAllProduct')->name('priority.getAllProduct');
            });
            Route::namespace('Users')->group(function () {
                Route::get('users', 'UsersController@index')->name('users.index');
                Route::get('users/create', 'UsersController@create')->name('users.create');
                Route::get('users/edit/{id}', 'UsersController@edit')->name('users.edit');
                Route::post('users/store', 'UsersController@store')->name('users.store');
                Route::post('users/destroy/{id}', 'UsersController@destroy')->name('users.destroy');
            });
            Route::namespace('Offers')->group(function () {
                Route::resource('offers', 'OffersController');
                Route::get('offers_product','OffersController@getProduct')->name('offers.product.attr');
                Route::post('offers/{id}', 'OffersController@update')->name('offers.update');
                Route::get('remove-image-offer', 'OffersController@removeImage')->name('offers.remove.image');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');

smartvent_git/resources/views/admin/crops/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.customers.store') }}" method="post" class="form">
                <div class="box-body">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{{ old('name') }}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="email" id="email" placeholder="Email" class="form-control" value="{{ old('email') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password">Password <span class="text-danger">*</span></label>
                        <input type="password" name="password" id="password" placeholder="xxxxx" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="mobile">Mobile <span class="text-danger">*</span></label>
                        <input type="text" name="mobile" id="mobile" placeholder="Mobile" class="form-control" value="{{ old('mobile') }}">
                    </div>
                    <div class="form-group">
                        <label for="status">Status </label>
                        <select name="status" id="status" class="form-control">
                            <option value="0">Disable</option>
                            <option value="1">Enable</option>
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.customers.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

smartvent_git/resources/views/admin/crops/edit.blade.php
@extends('layouts.admin.app')

@section('content')

    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <form action="{{ route('admin.customers.update', $customer->id) }}" method="post" class="form">
                <div class="box-body">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                        <label for="name">Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="{!! $customer->name ?: old('name')  !!}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="email" id="email" placeholder="Email" class="form-control" value="{!! $customer->email ?: old('email')  !!}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password">Password <span class="text-danger">*</span></label>
                        <input type="password" name="password" id="password" placeholder="xxxxx" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="mobile">Mobile <span class="text-danger">*</span></label>
                        <input type="text" name="mobile" id="mobile" placeholder="Mobile Number" class="form-control" value="{!! $customer->mobile ?: old('mobile')  !!}">
                    </div>
                    <div class="form-group">
                        <label for="status">Status </label>
                        <select name="status" id="status" class="form-control">
                            <option value="0" @if($customer->status == 0) selected="selected" @endif>Disable</option>
                            <option value="1" @if($customer->status == 1) selected="selected" @endif>Enable</option>
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('admin.customers.index') }}" class="btn btn-default btn-sm">Back</a>
                        <button type="submit" class="btn btn-primary btn-sm">Update</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

smartvent_git/resources/views/admin/crops/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($crops)
            <div class="box">
                <div class="box-body">
                    <h2>Crops</h2>
                    @include('layouts.search', ['route' => route('admin.crops.index')])
                    <table class="table">
                        <thead>
                            <tr>
                                <td class="col-md-1">ID</td>
                                <td class="col-md-2">Name</td>
                                <td class="col-md-2">Email</td>
                                <td class="col-md-2">Mobile</td>
                                <td class="col-md-2">Status</td>
                                <td class="col-md-3">Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($crops as $crop)
                            <tr>
                                <td>{{ $crop['id'] }}</td>
                                <td>{{ $crop['crop_category'] }}</td>
                                <td>{{ $crop['name'] }}</td>
                               <td>
                                    <form action="{{ route('admin.crops.destroy', $crop['id']) }}" method="post" class="form-horizontal">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            <a href="{{ route('admin.crops.show', $crop['id']) }}" class="btn btn-default btn-sm"><i class="fa fa-eye"></i> Show</a>
                                            <a href="{{ route('admin.crops.edit', $crop['id']) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $crops->links() }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection

smartvent_git/resources/views/admin/crops/show.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-body">
                <h2>Customer</h2>
                <table class="table">
                    <tbody>
                    <tr>
                        <td class="col-md-3">ID</td>
                        <td class="col-md-3">Name</td>
                        <td class="col-md-3">Email</td>
                        <td class="col-md-3">Mobile Number</td>
                    </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td>{{ $customer->id }}</td>
                        <td>{{ $customer->name }}</td>
                        <td>{{ $customer->email }}</td>
                        <td>{{ $customer->mobile }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="box-body">
                <h2>Addresses</h2>
                <table class="table">
                    <tbody>
                    <tr>
                        <td class="col-md-2">Alias</td>
                        <td class="col-md-2">Address 1</td>
                        <td class="col-md-2">Country</td>
                        <td class="col-md-2">Status</td>
                        <td class="col-md-4">Actions</td>
                    </tr>
                    </tbody>
                    <tbody>
                    @foreach ($addresses as $address)
                        <tr>
                            <td>{{ $address->alias }}</td>
                            <td>{{ $address->address_1 }}</td>
                            <td>{{ $address->country->name }}</td>
                            <td>@include('layouts.status', ['status' => $address->status])</td>
                            <td>
                                <form action="{{ route('admin.addresses.destroy', $address->id) }}" method="post" class="form-horizontal">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="delete">
                                    <div class="btn-group">
                                        <a href="{{ route('admin.customers.addresses.show', [$customer->id, $address->id]) }}" class="btn btn-default btn-sm"><i class="fa fa-eye"></i> Show</a>
                                        <a href="{{ route('admin.customers.addresses.edit', [$customer->id, $address->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="btn-group">
                    <a href="{{ route('admin.customers.index') }}" class="btn btn-default btn-sm">Back</a>
                </div>
            </div>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection