smartvent_git/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        // Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
                Route::post('getCategories', 'ProductController@getCategories')->name('products.getCategories');
                Route::post('getCropCategories', 'ProductController@getCropCategories')->name('products.getCropCategories');
                Route::post('getSubCropCategories', 'ProductController@getSubCropCategories')->name('products.getSubCropCategories');
                  Route::get('checkProductname', 'ProductController@checkProductname')->name('products.checkProductname');
                  Route::get('checkEditProductname', 'ProductController@checkEditProductname')->name('products.checkEditProductname');
                Route::post('getSubCategories', 'ProductController@getSubCategories')->name('products.getSubCategories');
                Route::get('checkhsncode', 'ProductController@checkHsnCode')->name('products.checkhsncode');
                Route::post('getTechnicalName', 'ProductController@getTechnicalName')->name('products.getTechnicalName');
                Route::post('getProductTechnical', 'ProductController@getProductTechnical')->name('products.getProductTechnical');

            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            // Route::namespace('Crop')->group(function () {
            //     Route::resource('crops', 'CropController');
            // });
            Route::namespace('Crops')->group(function () {
                Route::resource('crops', 'CropController');
                Route::get('crops/create/{id?}', 'CropController@create')->name('crops.create');
                Route::get('crops/subcrop/{id}/{subcat?}', 'CropController@showSub')->name('crops.show_sub');
                Route::get('crops/subcrop/create/{id?}/{subcat?}', 'CropController@subCreate')->name('crops.sub_create');
                Route::get('crops/getsubcat/{id}', 'CropController@getSubcat')->name('crops.getsubcat');
                Route::post('crops/substore', 'CropController@subStore')->name('crops.subcatstore');
                Route::get('crops/subcrop/edit/{id}/{cat}/{subcat}', 'CropController@subEdit')->name('crops.sub_edit');
                Route::get('checkSubsolutionname', 'CropController@checkSubsolutionname')->name('crops.checkSubsolutionname');
              Route::get('checkEditSubsolutionname', 'CropController@checkEditSubsolutionname')->name('crops.checkEditSubsolutionname');
                
            });
            
            Route::namespace('CustomerNotifications')->group(function () {
                Route::post('getValue', 'NotificationController@getValue')->name('notifications.getValue');
                Route::resource('notifications', 'NotificationController');
            });
            
            Route::namespace('TechnicalCategoties')->group(function () {
                Route::resource('technical', 'TechnicalController');
            });

            Route::namespace('UpdateStocks')->group(function () {
                Route::resource('updateStock', 'UpdateStockController');
            });
            
            
            Route::namespace('CountriesData')->group(function () {
                Route::resource('country_data', 'CountryDataController');
                Route::get('country_data/show-tehsil/{id?}', 'CountryDataController@showTehsil')->name('country_data.showTehsil');
                Route::get('country_data/show-village/{id?}', 'CountryDataController@showVillage')->name('country_data.showVillage');
                //Route::get('country_data/destroy-village/{id?}', 'CountryDataController@destroyVillage')->name('country_data.destroyVillage');
                Route::get('checkDistrictname', 'CountryDataController@checkDistrictname')->name('country_data.checkDistrictname');
                Route::get('checkEditDistrictname', 'CountryDataController@checkEditDistrictname')->name('country_data.checkEditDistrictname');
                Route::get('checkTehsilname', 'CountryDataController@checkTehsilname')->name('country_data.checkTehsilname');
                Route::get('checkEditTehsilname', 'CountryDataController@checkEditTehsilname')->name('country_data.checkEditTehsilname');
                Route::get('checkVillagename', 'CountryDataController@checkVillagename')->name('country_data.checkVillagename');
                Route::get('checkEditVillagename', 'CountryDataController@checkEditVillagename')->name('country_data.checkEditVillagename');
                Route::post('destroy/{id}', 'CountryDataController@destroy')->name('country_data.destroy');
                Route::post('destroydistrict/{id}', 'CountryDataController@destroydistrict')->name('country_data.destroydistrict');
                Route::post('destroytehsil/{id}', 'CountryDataController@destroytehsil')->name('country_data.destroytehsil');
                Route::post('country_data/destroyvillage/{id}', 'CountryDataController@destroyvillage')->name('country_data.destroyvillage');
                Route::post('getCity', 'CountryDataController@getCity')->name('country_data.getCity');
                Route::post('getTehsil', 'CountryDataController@getTehsil')->name('country_data.getTehsil');
                Route::get('createVillage','CountryDataController@createVillage')->name('country_data.createVillage');
                Route::get('createCity','CountryDataController@createCity')->name('country_data.createCity');
                Route::post('state-store','CountryDataController@stateStore')->name('country_data.state_store');
                
                // Disritct
                Route::get('disritct-edit/{id}','CountryDataController@disritctEdit')->name('country_data.disritct_edit');
                Route::post('disritct-update','CountryDataController@disritctUpdate')->name('country_data.disritct_update');
                
                // Edit Tehsil
                Route::get('tehsil-edit/{id}','CountryDataController@tehsilEdit')->name('country_data.tehsil_edit');
                Route::post('tehsil-store','CountryDataController@tehsilStore')->name('country_data.update_tehsil');
                
                // Village
                Route::get('village-edit/{id}','CountryDataController@villageEdit')->name('country_data.village_edit');
                Route::post('village-update','CountryDataController@villageUpdate')->name('country_data.village_update');
                
                
            });

            Route::namespace('Priorities')->group(function () {
                Route::resource('pro_priority', 'PriorityController');
                // Route::post('update', 'PriorityController@update');
                Route::post('pro_priority/sort', 'PriorityController@cat_sort')->name('priority.sort');
                Route::post('pro_priority/subcat_sort', 'PriorityController@subcat_sort')->name('priority.subcat_sort');
                Route::post('pro_priority/getProduct', 'PriorityController@getProduct')->name('priority.getProduct');
                Route::post('pro_priority/getCategoryProduct', 'PriorityController@getCategoryProduct')->name('priority.getCategoryProduct');
                Route::post('pro_priority/getAllProduct', 'PriorityController@getAllProduct')->name('priority.getAllProduct');
            });
            Route::namespace('Users')->group(function () {
                Route::get('users', 'UsersController@index')->name('users.index');
                Route::get('users/create', 'UsersController@create')->name('users.create');
                Route::get('users/edit/{id}', 'UsersController@edit')->name('users.edit');
                Route::post('users/store', 'UsersController@store')->name('users.store');
                Route::post('users/destroy/{id}', 'UsersController@destroy')->name('users.destroy');
            });
            Route::namespace('Offers')->group(function () {
                Route::resource('offers', 'OffersController');
                Route::get('offers_product','OffersController@getProduct')->name('offers.product.attr');
                Route::post('offers/{id}', 'OffersController@update')->name('offers.update');
                Route::get('remove-image-offer', 'OffersController@removeImage')->name('offers.remove.image');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');

smartvent_git/resources/views/admin/user-role/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        @include('layouts.errors-and-messages')
        <!-- Default box -->
        @if($employees)
        <div class="box">
            <div class="box-body">
                <div class="box-body">
                    <div class="box-header with-border bg-title border-header">
                        <h4 class="page-title header-color">Manage Users</h4>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table border-b1px" id="table-id">
                        <thead>
                            <tr>
                                <th class="col-md-1">ID</th>
                                <th class="col-md-3">Name</th>
                                <th class="col-md-3">Email</th>
                                <th class="col-md-2">Status</th>
                                <th class="col-md-3">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @php $i=1 @endphp
                        @foreach ($employees as $employee)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $employee->name }}</td>
                                <td>{{ $employee->email }}</td>
                                <td>@include('layouts.status', ['status' => $employee->status])</td>
                                <td>
                                    <form action="{{ route('admin.users.destroy', $employee->id) }}" method="post" class="form-horizontal">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="post">
                                        <div class="btn-group">
                                            @if($permission->edit==1)
                                                <a href="{{ route('admin.users.edit', $employee->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                            @endif
                                            @if($permission->delete==1)
                                                <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> </button>
                                            @endif
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="box-footer">
            <div class="box-body">
            </div>
        </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
        @else
            <div class="box">
                <div class="box-body"><p class="alert alert-warning">No Users found.</p></div>
            </div>
        @endif

    </section>
    <!-- /.content -->
@endsection

@section('js')
<script>
    $(document).ready(function() {
        $('#table-id').DataTable();
    } );
</script>
@endsection

smartvent_git/resources/views/admin/user-role/profile.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        @include('layouts.errors-and-messages')
        <div class="box">
            <div class="box-body">
                <div class="box-header with-border border-header">
                    <h2>Profile</h2>
                </div>
            </div>
            <form action="{{ route('admin.companies.profile.update', $employee->id) }}" id="edit_profile" method="post" class="form" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="put">
                {{ csrf_field() }}
                <!-- Default box -->
                <!--<div class="box">-->
                    <div class="box-body">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td class="col-md-3">Name</td>
                                    <td class="col-md-3">Email</td>
                                    <td class="col-md-3">Password</td>
                                    <td class="col-md-3">Profile Image</td>
                                </tr>
                            </tbody>
                            <tbody>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <input name="name" type="text" class="form-control" value="{{ $employee->name }}">
                                    </div>
                                </td>
                                <td>
                                    <div class="form-group">
                                        <input name="email" type="email" class="form-control" value="{{ $employee->email }}">
                                    </div>
                                </td>
                                <td>
                                    <div class="form-group">
                                        <input name="password" type="password" class="form-control" value="" placeholder="xxxxxx">
                                    </div>
                                </td>
                                <td>
                                    <div class="form-group">
                                        <input type="file" name="logo" id="logo" class="form-control" onchange="GetFileSize()">
                                        <label id="image_error" class="image_error">Image size is large.</label>
                                        <label id="image_type_error"  class="image_type_error">Select image only .jpg, .png, .jpeg file</label>
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="btn-group">
                            <a href="{{ route('admin.dashboard') }}" class="btn btn-default btn-sm">Back</a>
                            <button class="btn btn-success btn-sm" id="add_submit" type="submit"> <i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                <!--</div>-->
                <!-- /.box -->
            </form>
        </div>
    </section>
    <!-- /.content -->
@endsection

@section('js')

<script src="{{ asset('js/jquery.validate.js') }}"></script>
<script src="{{ asset('js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('js/additional-methods.min.js') }}"></script>

<script type="text/javascript">
    $("#edit_profile").validate({
        ignore: [],
        errorClass: 'error text-change',
        successClass: 'validation-valid-label',
        highlight: function (element, errorClass) {
            $(element).removeClass(errorClass);
        },
        unhighlight: function (element, errorClass) {
            $(element).removeClass(errorClass);
        },
        validClass: "validation-valid-label",
        rules: {
            name: {
                required: true,
                maxlength: 25,
            },
            email : {
                required: true,
                email: true,
            },
        },
        messages: {
            "name":{
                required: "Please enter name.",
                maxlength:"Please enter no more than 25 character.",
            },
            "email":{
                required: "Please enter email.",
                email: "Please enter a valid email address.",
            },
        },
            
        submitHandler: function (form) {
            $('#add_submit').attr('disabled', true);
            form.submit();
        },
    });
    function GetFileSize() {
        var fi = document.getElementById('logo');
        if (fi.files.length > 0) {
            for (var i = 0; i <= fi.files.length - 1; i++) {

                var fsize = fi.files.item(i).size;
                var type = fi.files.item(i).type;
                var size = fsize/1024;    
                if(size>1024){
                    document.getElementById('image_error').style.display="block";
                }
                if(type != 'image/png' || type != 'image/jpeg' || type != 'image/jpg'){
                    document.getElementById('image_type_error').style.display="block";
                }
            }
        }
    }
</script>
@endsection

smartvent_git/resources/views/admin/user-role/show.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-body">
                <table class="table" id="table-id">
                    <tbody>
                        <tr>
                            <td class="col-md-1">ID</td>
                            <td class="col-md-3">Name</td>
                            <td class="col-md-3">Email</td>
                            <td class="col-md-3">Logo</td>
                            <td class="col-md-2">Roles</td>
                        </tr>
                    </tbody>
                    <tbody>
                    <tr>
                        <td>{{ $employee->id }}</td>
                        <td>{{ $employee->name }}</td>
                        <td>{{ $employee->email }}</td>
                        <td>
                            @if(isset($employee->cover))
                                <img src="{{ asset("storage/$employee->cover") }}" class="img-responsive" alt="">
                            @endif
                        </td>
                        <td>
                            {{ $employee->roles()->get()->implode('name', ', ') }}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="btn-group">
                    <a href="{{ route('admin.companies.index') }}" class="btn btn-default btn-sm">Back</a>
                </div>
            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection